### ISSUE TITLE
Use with generators?

### ISSUE THREAD

**Issue by shellscape** [dcodeIO/node-harmonize#10]
Given the following example, harmonize doesn't seem to have any kind of an impact, as there's no way to bypass the `Unexpected token: *` syntax error:

``` javascript
require('harmonize')();

function* foo () {}
```

**Comment by dcodeIO** [comment]
On node 0.10 I am getting this error even if I manually run node with the "--harmony" flag. Are you sure that it is supported by your version of node?

**Comment by shellscape** [comment]
@dcodeIO current stable version of node is 0.12.6. time for an update ;) we use 0.12.6 across the tech org at this company.

**Comment by dcodeIO** [comment]
Well, I surely know that, just wanted to make sure.

To use generators (or any other syntax not supported by the host without the harmony flag) after calling harmonize, you have to require(..) the file that uses generator syntax as node parses the entry point file before executing anything.

See: https://github.com/dcodeIO/node-harmonize/blob/master/tests/test.js

**Comment by shellscape** [comment]
Right on. Suspected that was the case. Thanks for humoring the question, appreciated!
