### ISSUE TITLE
Flags are incorrectly ignored on iojs and node 0.12

### ISSUE THREAD

**Issue by bgw** [dcodeIO/node-harmonize#11]
This snippet of code is incorrect

``` js
// harmony flag is unnecessary in io and beginning with node v0.12
if(isIojs || (!isIojs && v[0] == 0 && v[1] > 12))
    return;
```

Because staging or in-progress features, like arrow functions and proxies, still have to be explicitly enabled.

**Comment by dcodeIO** [comment]
Closing this for now. See harmonize@2.0.0
