### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by gagern** [dcodeIO/node-harmonize#12]
In 6701b9cb6a8d68c2cbcf1994bf028db4ce2b4ba2, the version of harmonize changed from 1.33.7 to 1.4.0. According to the rules of [semantic versioning](https://docs.npmjs.com/getting-started/semantic-versioning), this is going back in time! It can lead to strange results:

```
$ npm install --save harmonize
harmonize@1.4.4 node_modules/harmonize
└── is-iojs@1.1.0
$ npm update
harmonize@1.33.7 node_modules/harmonize
```

This is because 1.33.7 is the highest version matching the default `^1.4.4` version range, even if `1.4.4` is the latest one to be published to the registry. I think you should release a new version, and name that 1.34.0, just to get versioning right again.

**Comment by dcodeIO** [comment]
Closing this for now. See harmonize@2.0.0
