### ISSUE TITLE
Harmonize Still Relevant After v0.12

### ISSUE THREAD

**Issue by shellscape** [dcodeIO/node-harmonize#13]
Harmonize is still relevant, despite the original intent of the module to get us over the Proxy and Generators hurdles. With features like async/await being hid behind harmony flags, harmonize maintains its relevancy.

However, because there are blockers setup based on 0.12 harmony assumptions, it's not possible to use it for current-day needs.

https://github.com/dcodeIO/node-harmonize/blob/master/harmonize.js#L31 looks for `Proxy` which is defined in v7, for example.

https://github.com/dcodeIO/node-harmonize/blob/master/harmonize.js#L34 checks for a version number greater than 0.12 and bails if found.

Would you welcome a pull request?
Would you like to transfer the project?
Would you prefer a fork and new module?

Would love to contribute, but given that this module is quite aged, I'm happy to go down whatever road you'd prefer.

**Comment by dcodeIO** [comment]
I've seen your progress on supporting newer versions of node - really cool! If you like, you can take over the harmonize module name, but your first release should be a v2 to not confuse semver unnecessarily.

**Comment by shellscape** [comment]
@dcodeIO admittedly fueled by some really good whiskey, I ended up releasing a new module (harmonica) to support node 4.6.2 and up. I've got full attribution to you and the project up on the README. if there's anything you'd like me to add, say the word and it shall be done.
