### ISSUE TITLE
Version 1.33.7 causes gulp to timeout in old versions of node

### ISSUE THREAD

**Issue by remojansen** [dcodeIO/node-harmonize#14]
Version 1.33.7 causes gulp to timeout in old versions of node. Build example: https://travis-ci.org/inversify/InversifyJS/builds/187246937

**Comment by dcodeIO** [comment]
This module hasn't been updated for a while. Maybe try https://github.com/shellscape/harmonica instead

**Comment by dcodeIO** [comment]
Closing this for now. See harmonize@2.0.0

**Comment by remojansen** [comment]
The version 2.0 [fails](https://travis-ci.org/inversify/InversifyJS/builds/187308976) but this time with a different error:

> Error: Native proxies not enabled. use `node --harmony-proxies` to enable them.

It works fine with `harmonize@1.4.4`.

**Comment by dcodeIO** [comment]
Have you tried

```js
require("harmonize")(["harmony", "harmony-proxies", "harmony_proxies"]);
// not exactly sure why it's --harmony-proxies sometimes
// v8-options shows --harmony_proxies for me with node 6.9.1
```

already? 2.0 does not set anything but `--harmony` by default.

**Comment by remojansen** [comment]
That solved my problem! Thanks a lot for your help 👍
