### ISSUE TITLE
Allow activating only specific features

### ISSUE THREAD

**Issue by ghost** [dcodeIO/node-harmonize#8]
Since `--harmony` enables both [stable and less stable features in node](https://iojs.org/en/es6.html), it would be nice to be able to pass options to harmonize. Allowing you to specify which features you want to enable exactly (for example, just `--harmony-generators`).

**Comment by dcodeIO** [comment]
Please let me know if this does the trick for you.

**Comment by ghost** [comment]
I've tested it, but the new build hangs whenever I try to use harmonize (100% disk and cpu activity). My test is here: https://github.com/superwolff/cape/tree/test-harmonize and [this](https://github.com/superwolff/cape/blob/test-harmonize/gulpfile.js) is where I'm using harmonize. Because it hangs I wasn't able to get any errors, unfortunately.

**Comment by dcodeIO** [comment]
Tested this, and on node v0.10 this turns into an endless loop because of

```
Error: unrecognized flag --harmony-generators
Try --help for options
```

**Comment by ghost** [comment]
Weird, because I should be running 0.12:

``` bash
╰─$ nvm ls
    iojs-v1.8.1
       v0.10.38
->      v0.12.2
default -> stable (-> v0.12.2)
node -> stable (-> v0.12.2) (default)
stable -> 0.12 (-> v0.12.2) (default)
iojs -> iojs-v1.8 (-> iojs-v1.8.1) (default)
```

**Comment by ghost** [comment]
With your new commits (and my unchanged code) I'm getting this error:

```
/home/ismay/Github/cape/node_modules/harmonize/harmonize.js:44
            features = features.map(function(feat) {
                                ^
TypeError: undefined is not a function
    at module.exports (/home/ismay/Github/cape/node_modules/harmonize/harmonize.js:44:30)
    at Object.<anonymous> (/home/ismay/Github/cape/gulpfile.js:5:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/home/ismay/.nvm/versions/node/v0.12.2/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/ismay/.nvm/versions/node/v0.12.2/lib/node_modules/gulp/node_modules/liftoff/index.js:181:16)
```

But I couldn't find a clear error in your code, it looks good to me at a glance..

**Comment by ghost** [comment]
Any idea what's the reason for `.map` to throw an error? Is it something I'm overlooking?

**Comment by dcodeIO** [comment]
I made this more resilient now and also pushed the new version to npm. Let me know if it is working for you.

**Comment by ghost** [comment]
Tested 1.4.4, and works as expected for me. Awesome!
